### ISSUE TITLE
Scoreboxes don´t adding points

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#123]
http://youtu.be/1LNVVjHEWWg

**Comment by CaptainElliott** [comment]
The scorebox module has not yet been implemented

**Comment by Alfalik** [comment]
Giving an error when stay on it.

http://youtu.be/lR2sdkb33Nw
http://gyazo.com/00bb9a7c6413f2c5db7e0d19d878a878

**Comment by twizmwazin** [comment]
@Alfalik Is the error with the unmodified XML?

**Comment by Alfalik** [comment]
Tested with maps.oc.tc xml & removing portals xml. Same error.

**Comment by twizmwazin** [comment]
Ok, I think I found the issue

**Comment by twizmwazin** [comment]
The issue should be fixed in 1a7ed5b684833819e0af140d0846774923ac487c

**Comment by iEli2tyree011** [comment]
@twizmwazin It's not fixed, at least for Facility. It now looks to be an issue with MirroredRegions though.

**Comment by twizmwazin** [comment]
It was fixed in my test, I joined red and used the right scorebox.

**Comment by Alfalik** [comment]
Not fixed, when walking the console is being spammed. I don´t know if is realted with scoreboxes.

**Comment by twizmwazin** [comment]
I will double check

**Comment by Alfalik** [comment]
The normal Facility don´t have mirror regions.

**Comment by twizmwazin** [comment]
It appears the issue is with Mirrored regions used for portals, and is not related to the scorebox module.

**Comment by Alfalik** [comment]
Should I create an issue?

**Comment by twizmwazin** [comment]
We are working on it, there is no need.
