### ISSUE TITLE
Incompatibilty with CommandBook

### ISSUE THREAD

**Issue by RubeGamerV** [twizmwazin/CardinalPGM#176]

**Comment by ItzWid13** [comment]
Its good the command book :c

**Comment by twizmwazin** [comment]
Are you using Overcast's version of command book?

**Comment by RubeGamerV** [comment]
No, do exist one?

**Comment by twizmwazin** [comment]
https://repo.oc.tc/content/repositories/snapshots/com/sk89q/commandbook/2.5-SNAPSHOT/commandbook-2.5-20140901.220343-3.zip

The issue is because SportBukkit 1.7.10 uses an updated version of the Guava library.

**Comment by RubeGamerV** [comment]
Thanks

**Comment by RubeGamerV** [comment]
But when i edit the config.yml from CommandBook, this recreate and override the config

**Comment by twizmwazin** [comment]
Are you saying that config options aren't persistent between restarts?

**Comment by RubeGamerV** [comment]
yes

**Comment by RubeGamerV** [comment]
@twizmwazin  Yes

**Comment by AngelCasillas01** [comment]
@twizmwazin You can't use SA2 too, it's true what he are saying, i edit all i can, almost all plugins arent working, LegendaryRestart arent working :(

**Comment by twizmwazin** [comment]
@AngelCasillas01 These issues have nothing to do with Cardinal, but rather with Sportbukkit. Because Cardinal is designed to be a primarily standalone plugin, we are not concerned with some other plugins.  I believe that some of these issues will be resolved with Sportbukkit 1.8, as it appears that it will use the same Guava version as Craftbukkit/Spigot.

**Comment by AngelCasillas01** [comment]
Ok, I'll understand, but It's true what he are saying about CommandBook on config.yml, i tested on some servers without cardinal, the same, i try with CraftBukkit too with only CommandBook on plugins folder, the same, do you know why? Because i'm confused :c

**Comment by AngelCasillas01** [comment]
@twizmwazin

**Comment by twizmwazin** [comment]
The config issue should be resolved in b06d5759d0ca2eced699dc5219f4c09e8be71ba2. Cardinal is not compatible with Craftbukkit. For CommandBook you need to use Overcast's version for 1.7.10. Cardinal will soon be updating to be 1.8 only, and then the issue should be fixed.

**Comment by AngelCasillas01** [comment]
@twizmwazin Nice to heard Good News every time i talk to you :)

**Comment by RubeGamerV** [comment]
@twizmwazin i use Overcast´s s sportbukkit 1.7.10 SNAPSHOT
 and the problem still

**Comment by twizmwazin** [comment]
@RubeGamerV I know. If you want CommandBook to work with SportBukkit, you must use Overcast's CommandBook, linked earlier in the issue. Normal CommandBook does not work with Sportbukkit.

**Comment by AngelCasillas01** [comment]
@twizmwazin i got the sameone that you give it and the same problem :c does i need to do something before?

**Comment by twizmwazin** [comment]
If the issue is not resolved, I will try to resolve the issue when everything is updated to 1.8.

**Comment by RubeGamerV** [comment]
@twizmwazin and you add the UUID support from xml contributors in the 1.8?

**Comment by AngelCasillas01** [comment]
@twizmwazin  so now we should wait SportBukkit 1.8 to this problem been solved, it's ok! Maybe more problems will be solved after the release, does this update will afect the plugin?

**Comment by twizmwazin** [comment]
@AngelCasillas01 Yes, I will have to make a few changes to Cardinal to support 1.8, meaning Cardinal will not work with 1.7.10 after 1.8 comes out.

**Comment by AngelCasillas01** [comment]
@twizmwazin Sooooo, that means we can't use 1.7.2 after SportBukkit 1.8 comes released D: or you will update Cardinal to 1.8 but we can still use 1.7.2 :D

**Comment by twizmwazin** [comment]
Right now, Cardinal is only tested against 1.7.10. When we update to 1.8, Cardinal will work only with 1.8, not 1.7.10 or 1.7.2.

**Comment by AngelCasillas01** [comment]
@twizmwazin i understand now! Nice to heard you are exited to upgrade

**Comment by RubeGamerV** [comment]
@twizmwazin <a href="http://gyazo.com/a2eb894498e460f1905f82b794e6eb94"><img src="http://i.gyazo.com/a2eb894498e460f1905f82b794e6eb94.png" /></a> when i try to use the last SNAPSHOT of Commandbook with the cardinal

**Comment by twizmwazin** [comment]
@RubeGamerV Where did you download this snapshot from? This issue is completely unrelated to Cardinal.

**Comment by RubeGamerV** [comment]
@twizmwazin from here <a href"https://repo.oc.tc/content/repositories/snapshots/com/sk89q/commandbook/">here</a>

**Comment by Superjd10** [comment]
@RubeGamerV He means where did you download the CardinalPGM snapshot? Because it's trying to stop "AwesomePGM" instead of "CardinalPGM" (5 last line)

**Comment by RubeGamerV** [comment]
@Superjd10  es por que es el mejor PGM :D por eso es Awesome

**Comment by Alfalik** [comment]
@RubeGamerV Le quitas crédito a los autores cambiando el nombre del plugin con eclipse, ademas de crear errores.

**Comment by RubeGamerV** [comment]
@Alfalik  Para empezar no lo estoy poniendo a descarga con mi credito y nunca dije que es a mi nombre

**Comment by twizmwazin** [comment]
@RubeGamerV Please don't re-upload my (and others') work. I will not provide any support for it. Regardless, you must include my copyright notice found {here] (https://github.com/twizmwazin/CardinalPGM/blob/master/LICENSE). Failure to do so will result in a DMCA.

**Comment by Alfalik** [comment]
@RubeGamerV Entonces para que le cambias el nombre, es algo total y completamente innecesario, ademas, desvaloras el trabajo de los autores.

**Comment by RubeGamerV** [comment]
@Alfalik pero no lo estoy vendiendo ni ofreciendo, simplemente le cambie el nombre y no me estoy robando el credito, en el archivo plugin.yml te aparese el nombre y si lo cambie es porque quiero ver como se mira asi y si lo cambio a ti no te debe de importar

**Comment by Superjd10** [comment]
@RubeGamerV Por cambiarle el nombre no puedes recibir ayuda por parte de los desarrolladores, ellos dan soporte a lo que ellos hacen, tal y como ellos lo hacen, sin ediciones.

**Comment by RubeGamerV** [comment]
@Superjd10 pues ellos lo hicieron yo solo vi que se podia cambiar el nombre y lo hice, pero eso no cambia que lo hicieron ellos

**Comment by elespawol** [comment]
Es verdad... les quitas merito a los creadores de plugin...
Si quieres... lo LEGAL q podrias hacer, es con un plugin bloquear el
/plugins para q evitasen ver q PGM usas... pero bueno... alla tu
Si tu fueras el autor, seguramente no te.aria gracia lo q has hecho
(Vamos.. eso creo)

@RubeGamerV <https://github.com/RubeGamerV> Primero que nada hiciste un
repositorio en github poniendo nombres como BHPGM & AwesomePermissions, no
se que quieres hacer con ellos, pero no creo que tu seas capaz de crear una
copia del plugin PGM, o simplemente un archivo java, siento que harás lo
mismo que algunos hicieron con el Spork, cambiar el nombre y decir que
ellos (tú en este caso) crearon el plugin. Segundo, y vuelvo a repetir, no
tiene caso cambiarle el nombre a cualquier plugin, solo creas errores y
desvaloras el trabajo de los autores.

—
Reply to this email directly or view it on GitHub
<https://github.com/twizmwazin/CardinalPGM/issues/176#issuecomment-75134764>
.
